import { EventEmitter, Injector, OnInit } from '@angular/core';
import { FormControl, FormGroup, ValidatorFn } from '@angular/forms';
import { OTableColumn } from '../../../../interfaces/o-table-column.interface';
import { SnackBarService } from '../../../../services/snackbar.service';
import { OTranslateService } from '../../../../services/translate/o-translate.service';
import { OTableComponent } from '../../o-table.component';
export declare const DEFAULT_INPUTS_O_TABLE_CELL_EDITOR: string[];
export declare const DEFAULT_OUTPUTS_O_TABLE_CELL_EDITOR: string[];
export declare class OBaseTableCellEditor implements OnInit {
    protected injector: Injector;
    protected translateService: OTranslateService;
    orequired: boolean;
    showPlaceHolder: boolean;
    olabel: string;
    updateRecordOnEdit: boolean;
    showNotificationOnEdit: boolean;
    protected _enabled: boolean;
    protected _tableColumn: OTableColumn;
    protected _table: OTableComponent;
    protected _rowData: any;
    formControl: FormControl;
    controlArgs: any;
    formGroup: FormGroup;
    editionStarted: EventEmitter<object>;
    editionCancelled: EventEmitter<object>;
    editionCommitted: EventEmitter<object>;
    onPostUpdateRecord: EventEmitter<object>;
    editorCreated: EventEmitter<object>;
    inputRef: any;
    protected type: string;
    registerInColumn: boolean;
    protected snackBarService: SnackBarService;
    protected oldValue: any;
    onDocumentKeyup(event: KeyboardEvent): void;
    constructor(injector: Injector);
    ngOnInit(): void;
    initialize(): void;
    protected handleKeyup(event: KeyboardEvent): void;
    createFormControl(): void;
    registerEditor(): void;
    getCellData(): any;
    startEdition(data: any): void;
    endEdition(saveChanges: any): void;
    commitEdition(): void;
    tableColumn: OTableColumn;
    readonly tableColumnAttr: string;
    table: OTableComponent;
    rowData: any;
    resolveValidators(): ValidatorFn[];
    hasError(error: string): boolean;
    hasErrorExclusive(error: string): boolean;
    getErrorValue(error: string, prop: string): string;
    onEscClicked(): void;
    protected isSilentControl(): boolean;
    getPlaceholder(): string;
    protected onUpdateSuccess(res: any): void;
    enabled: boolean;
    getFormControl(): FormControl;
}
