import { Overlay, OverlayRef, ScrollStrategyOptions } from '@angular/cdk/overlay';
import { ChangeDetectorRef, ElementRef, EventEmitter, KeyValueDiffer, KeyValueDiffers, NgZone, ViewContainerRef, OnDestroy } from '@angular/core';
import { MatDialog } from '@angular/material';
import * as _moment from 'moment';
export declare class ODaterangepickerDirective implements OnDestroy {
    private _dialog;
    private _ngZone;
    private _overlay;
    _viewContainerRef: ViewContainerRef;
    _changeDetectorRef: ChangeDetectorRef;
    _el: ElementRef;
    private differs;
    private scrollStrategy;
    private _onChange;
    private _onTouched;
    _validatorChange: Function;
    private _value;
    localeDiffer: KeyValueDiffer<string, any>;
    minDate: _moment.Moment;
    maxDate: _moment.Moment;
    showCustomRangeLabel: boolean;
    linkedCalendars: boolean;
    dateLimit: number;
    singleDatePicker: boolean;
    showWeekNumbers: boolean;
    showISOWeekNumbers: boolean;
    showDropdowns: boolean;
    isInvalidDate: () => boolean;
    isCustomDate: () => boolean;
    opens: string;
    drops: string;
    firstMonthDayClass: string;
    lastMonthDayClass: string;
    emptyWeekRowClass: string;
    firstDayOfNextMonthClass: string;
    lastDayOfPreviousMonthClass: string;
    keepCalendarOpeningWithRange: boolean;
    showRangeLabelOnInput: boolean;
    showCancel: boolean;
    timePicker: boolean;
    showRanges: boolean;
    timePicker24Hour: boolean;
    timePickerIncrement: number;
    timePickerSeconds: boolean;
    _locale: any;
    _separator: string;
    separator: any;
    locale: any;
    private _endKey;
    private _startKey;
    ranges: any;
    oTouchUi: boolean;
    startKey: string;
    endKey: string;
    notForChangesProperty: Array<string>;
    value: any;
    onChange: EventEmitter<object>;
    rangeClicked: EventEmitter<object>;
    datesUpdated: EventEmitter<object>;
    private _popupComponentRef;
    private _calendarPortal;
    _popupRef: OverlayRef;
    private _dialogRef;
    constructor(_dialog: MatDialog, _ngZone: NgZone, _overlay: Overlay, _viewContainerRef: ViewContainerRef, _changeDetectorRef: ChangeDetectorRef, _el: ElementRef, differs: KeyValueDiffers, scrollStrategy: ScrollStrategyOptions);
    initializeListeners(instance: any): void;
    onBlur(): void;
    open(): void;
    ngOnDestroy(): void;
    clear(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setValueInDateComponent(instance: any, val: any): void;
    private setValue;
    openAsPopup(): void;
    private _createPopup;
    private _createPopupPositionStrategy;
    openAsDialog(): void;
    close(): void;
}
