import { AfterViewInit, ElementRef, EventEmitter, Injector, OnDestroy, OnInit, QueryList, TemplateRef } from '@angular/core';
import { MatCheckboxChange, MatDialog, MatMenu, MatPaginator, MatTab, MatTabGroup, PageEvent } from '@angular/material';
import { Observable, Subscription } from 'rxjs';
import { OTableButton } from '../../interfaces/o-table-button.interface';
import { OTableButtons } from '../../interfaces/o-table-buttons.interface';
import { OTableDataSource } from '../../interfaces/o-table-datasource.interface';
import { OTableMenu } from '../../interfaces/o-table-menu.interface';
import { OTableOptions } from '../../interfaces/o-table-options.interface';
import { OTablePaginator } from '../../interfaces/o-table-paginator.interface';
import { OTableQuickfilter } from '../../interfaces/o-table-quickfilter.interface';
import { SnackBarService } from '../../services/snackbar.service';
import { Expression } from '../../types/expression.type';
import { OColumnAggregate } from '../../types/o-column-aggregate.type';
import { OPermissions } from '../../types/o-permissions.type';
import { OTableInitializationOptions } from '../../types/o-table-initialization-options.type';
import { OTableMenuPermissions } from '../../types/o-table-menu-permissions.type';
import { OTablePermissions } from '../../types/o-table-permissions.type';
import { OQueryDataArgs } from '../../types/query-data-args.type';
import { QuickFilterFunction } from '../../types/quick-filter-function.type';
import { SQLOrder } from '../../types/sql-order.type';
import { OContextMenuComponent } from '../contextmenu/o-context-menu.component';
import { OFormComponent } from '../form/o-form.component';
import { OServiceComponent } from '../o-service-component.class';
import { OTableColumnCalculatedComponent } from './column/calculated/o-table-column-calculated.component';
import { OColumn } from './column/o-column.class';
import { OTableColumnComponent } from './column/o-table-column.component';
import { OTableFilterByColumnDataDialogComponent } from './extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component';
import { OTableColumnsFilterComponent } from './extensions/header/table-columns-filter/o-table-columns-filter.component';
import { OTableInsertableRowComponent } from './extensions/header/table-insertable-row/o-table-insertable-row.component';
import { OTableOptionComponent } from './extensions/header/table-option/o-table-option.component';
import { OTableStorage } from './extensions/o-table-storage.class';
import { OTableDao } from './extensions/o-table.dao';
import { OMatSort } from './extensions/sort/o-mat-sort';
import { OMatSortHeader } from './extensions/sort/o-mat-sort-header';
export declare const DEFAULT_INPUTS_O_TABLE: string[];
export declare const DEFAULT_OUTPUTS_O_TABLE: string[];
export declare class OTableComponent extends OServiceComponent implements OnInit, OnDestroy, AfterViewInit {
    protected dialog: MatDialog;
    static DEFAULT_BASE_SIZE_SPINNER: number;
    static FIRST_LAST_CELL_PADDING: number;
    protected snackBarService: SnackBarService;
    paginator: OTablePaginator;
    matpaginator: MatPaginator;
    sort: OMatSort;
    protected sortHeaders: QueryList<OMatSortHeader>;
    spinnerContainer: ElementRef;
    readonly diameterSpinner: number;
    tableContextMenu: OContextMenuComponent;
    selectAllCheckbox: boolean;
    exportButton: boolean;
    showConfigurationOption: boolean;
    columnsVisibilityButton: boolean;
    showFilterOption: boolean;
    showButtonsText: boolean;
    protected _oTableOptions: OTableOptions;
    oTableOptions: OTableOptions;
    quickFilter: boolean;
    protected filterCaseSensitivePvt: boolean;
    filterCaseSensitive: boolean;
    insertButton: boolean;
    refreshButton: boolean;
    deleteButton: boolean;
    paginationControls: boolean;
    fixedHeader: boolean;
    showTitle: boolean;
    editionMode: string;
    selectionMode: string;
    horizontalScroll: boolean;
    showPaginatorFirstLastButtons: boolean;
    autoAlignTitles: boolean;
    multipleSort: boolean;
    orderable: boolean;
    resizable: boolean;
    autoAdjust: boolean;
    protected _enabled: boolean;
    enabled: boolean;
    protected _selectAllCheckboxVisible: boolean;
    selectAllCheckboxVisible: boolean;
    keepSelectedItems: boolean;
    exportMode: string;
    exportServiceType: string;
    visibleExportDialogButtons: string;
    daoTable: OTableDao | null;
    dataSource: OTableDataSource | null;
    visibleColumns: string;
    sortColumns: string;
    rowClass: (rowData: any, rowIndex: number) => string | string[];
    protected _visibleColArray: Array<string>;
    visibleColArray: Array<any>;
    sortColArray: Array<SQLOrder>;
    protected tabGroupContainer: MatTabGroup;
    protected tabContainer: MatTab;
    tabGroupChangeSubscription: Subscription;
    protected pendingQuery: boolean;
    protected pendingQueryFilter: any;
    protected setStaticData: boolean;
    protected avoidQueryColumns: Array<any>;
    protected asyncLoadColumns: Array<any>;
    protected asyncLoadSubscriptions: object;
    protected querySubscription: Subscription;
    protected contextMenuSubscription: Subscription;
    protected finishQuerySubscription: boolean;
    onClick: EventEmitter<any>;
    onDoubleClick: EventEmitter<any>;
    onRowSelected: EventEmitter<any>;
    onRowDeselected: EventEmitter<any>;
    onRowDeleted: EventEmitter<any>;
    onDataLoaded: EventEmitter<any>;
    onPaginatedDataLoaded: EventEmitter<any>;
    onReinitialize: EventEmitter<any>;
    onContentChange: EventEmitter<any>;
    onVisibleColumnsChange: EventEmitter<any>;
    protected selectionChangeSubscription: Subscription;
    oTableFilterByColumnDataDialogComponent: OTableFilterByColumnDataDialogComponent;
    oTableColumnsFilterComponent: OTableColumnsFilterComponent;
    showFilterByColumnIcon: boolean;
    private showTotalsSubject;
    showTotals: Observable<boolean>;
    private loadingSortingSubject;
    protected loadingSorting: Observable<boolean>;
    private loadingScrollSubject;
    loadingScroll: Observable<boolean>;
    oTableInsertableRowComponent: OTableInsertableRowComponent;
    showFirstInsertableRow: boolean;
    showLastInsertableRow: boolean;
    protected clickTimer: any;
    protected clickDelay: number;
    protected clickPrevent: boolean;
    protected editingCell: any;
    protected editingRow: any;
    protected _currentPage: number;
    currentPage: number;
    oTableQuickFilterComponent: OTableQuickfilter;
    protected sortSubscription: Subscription;
    protected onRenderedDataChange: Subscription;
    protected previousRendererData: any;
    quickFilterCallback: QuickFilterFunction;
    protected tableBodyEl: ElementRef;
    tableHeaderEl: ElementRef;
    tableToolbarEl: ElementRef;
    horizontalScrolled: boolean;
    onUpdateScrolledState: EventEmitter<any>;
    rowWidth: any;
    oTableStorage: OTableStorage;
    storePaginationState: boolean;
    pageScrollVirtual: number;
    protected permissions: OTablePermissions;
    matMenu: MatMenu;
    oTableMenu: OTableMenu;
    tableOptions: QueryList<OTableOptionComponent>;
    oTableButtons: OTableButtons;
    tableButtons: QueryList<OTableButton>;
    quickfilterContentChild: OTableQuickfilter;
    exportOptsTemplate: TemplateRef<any>;
    updateScrolledState(): void;
    constructor(injector: Injector, elRef: ElementRef, dialog: MatDialog, form: OFormComponent);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    getSuffixColumnInsertable(): string;
    getActionsPermissions(): OPermissions[];
    getMenuPermissions(): OTableMenuPermissions;
    getOColumnPermissions(attr: string): OPermissions;
    protected getActionPermissions(attr: string): OPermissions;
    protected checkEnabledActionPermission(attr: string): boolean;
    initialize(): any;
    protected initializeDao(): void;
    reinitialize(options: OTableInitializationOptions): void;
    protected initTableAfterViewInit(): void;
    destroy(): void;
    getDataToStore(): {
        filter: string;
    };
    registerQuickFilter(arg: any): void;
    registerPagination(value: OTablePaginator): void;
    registerContextMenu(value: OContextMenuComponent): void;
    registerDefaultColumn(column: string): void;
    registerColumn(column: OTableColumnComponent | OTableColumnCalculatedComponent | any): void;
    protected pushOColumnDefinition(colDef: OColumn): void;
    protected refreshEditionModeWarn(): void;
    registerColumnAggregate(column: OColumnAggregate): void;
    parseVisibleColumns(): void;
    checkChangesVisibleColummnsInInitialConfiguration(stateCols: any): any;
    parseSortColumns(): void;
    initializeParams(): void;
    registerTabListener(): void;
    protected insideTabBugWorkaround(): void;
    registerSortListener(): void;
    protected onSortChange(sortArray: any[]): void;
    setDatasource(): void;
    protected registerDataSourceListeners(): void;
    readonly showLoading: Observable<any>;
    queryData(filter?: any, ovrrArgs?: OQueryDataArgs): void;
    protected isInsideInactiveTab(): boolean;
    getComponentFilter(existingFilter?: any): any;
    protected getQuickFilterExpression(): Expression;
    protected getColumnFiltersExpression(): Expression;
    updatePaginationInfo(queryRes: any): void;
    protected setData(data: any, sqlTypes: any): void;
    showDialogError(error: string, errorOptional?: string): void;
    projectContentChanged(): void;
    getAttributesValuesToQuery(): Array<string>;
    getQueryArguments(filter: object, ovrrArgs?: OQueryDataArgs): Array<any>;
    getSqlTypesForFilter(filter: any): object;
    onExportButtonClicked(): void;
    onChangeColumnsVisibilityClicked(): void;
    onMatTableContentChanged(): void;
    add(): void;
    remove(clearSelectedItems?: boolean): void;
    refresh(): void;
    showAndSelectAllCheckbox(): void;
    reloadPaginatedDataFromStart(): void;
    reloadData(): void;
    handleClick(item: any, $event?: any): void;
    doHandleClick(item: any, $event?: any): void;
    handleMultipleSelection(item: any): void;
    protected saveDataNavigationInLocalStorage(): void;
    handleDoubleClick(item: any, event?: any): void;
    readonly editionEnabled: boolean;
    handleDOMClick(event: any): void;
    handleCellClick(column: OColumn, row: any, event?: any): void;
    handleCellDoubleClick(column: OColumn, row: any, event?: any): void;
    protected activateColumnEdition(column: OColumn, row: any, event?: any): void;
    updateCellData(column: OColumn, data: any, saveChanges: boolean): Observable<any>;
    protected getKeysValues(): any[];
    onShowsSelects(): void;
    initializeCheckboxColumn(): void;
    protected updateSelectionColumnState(): void;
    isAllSelected(): boolean;
    masterToggle(event: MatCheckboxChange): void;
    selectAll(): void;
    selectionCheckboxToggle(event: MatCheckboxChange, row: any): void;
    selectedRow(row: any): void;
    readonly showDeleteButton: boolean;
    getTrackByFunction(): (index: number, item: any) => string;
    queryRowAsyncData(rowIndex: number, rowData: any): void;
    getValue(): any[];
    getAllValues(): any[];
    getAllRenderedValues(): any[];
    getRenderedValue(): any[];
    getSqlTypes(): any;
    setOTableColumnsFilter(tableColumnsFilter: OTableColumnsFilterComponent): void;
    getStoredColumnsFilters(): any;
    onFilterByColumnClicked(): void;
    onStoreFilterClicked(): void;
    onLoadFilterClicked(): void;
    onClearFilterClicked(): void;
    clearFilters(triggerDatasourceUpdate?: boolean): void;
    isColumnFilterable(column: OColumn): boolean;
    isModeColumnFilterable(column: OColumn): boolean;
    isColumnFilterActive(column: OColumn): boolean;
    openColumnFilterDialog(column: OColumn, event: Event): void;
    readonly disableTableMenuButton: boolean;
    readonly showTableMenuButton: boolean;
    setOTableInsertableRow(tableInsertableRow: OTableInsertableRowComponent): void;
    clearSelectionAndEditing(): void;
    useDetailButton(column: OColumn): boolean;
    onDetailButtonClick(column: OColumn, row: any, event: any): void;
    getDetailButtonIcon(column: OColumn): string;
    usePlainRender(column: OColumn, row: any): boolean;
    useCellRenderer(column: OColumn, row: any): boolean;
    useCellEditor(column: OColumn, row: any): boolean;
    isSelectionModeMultiple(): boolean;
    isSelectionModeSingle(): boolean;
    isSelectionModeNone(): boolean;
    onChangePage(evt: PageEvent): void;
    getOColumn(attr: string): OColumn;
    insertRecord(recordData: any, sqlTypes?: object): Observable<any>;
    updateRecord(filter: any, updateData: any, sqlTypes?: object): Observable<any>;
    getDataArray(): any[];
    setDataArray(data: Array<any>): void;
    protected deleteLocalItems(): void;
    isColumnSortActive(column: OColumn): boolean;
    isColumnDescSortActive(column: OColumn): boolean;
    hasTabGroupChangeSubscription(): boolean;
    isEmpty(value: any): boolean;
    setFiltersConfiguration(conf: any): void;
    onStoreConfigurationClicked(): void;
    onApplyConfigurationClicked(): void;
    applyDefaultConfiguration(): void;
    applyConfiguration(configurationName: string): void;
    getTitleAlignClass(oCol: OColumn): any;
    getCellAlignClass(column: OColumn): string;
    onTableScroll(e: any): void;
    getDataScrollable(): any;
    hasScrollableContainer(): boolean;
    protected addDefaultRowButtons(): void;
    protected addButtonInRow(name: string): void;
    readonly headerHeight: number;
    isDetailMode(): boolean;
    copyAll(): void;
    copySelection(): void;
    viewDetail(item: any): void;
    editDetail(item: any): void;
    getOColumnFromTh(th: any): OColumn;
    getColumnInsertable(name: any): string;
    isRowSelected(row: any): boolean;
    protected getColumnsWidthFromDOM(): void;
    refreshColumnsWidth(): void;
    private createOColumn;
}
