export declare class SQLTypes {
    static BIT: number;
    static TINYINT: number;
    static SMALLINT: number;
    static INTEGER: number;
    static BIGINT: number;
    static FLOAT: number;
    static REAL: number;
    static DOUBLE: number;
    static NUMERIC: number;
    static DECIMAL: number;
    static CHAR: number;
    static VARCHAR: number;
    static LONGVARCHAR: number;
    static DATE: number;
    static TIME: number;
    static TIMESTAMP: number;
    static BINARY: number;
    static VARBINARY: number;
    static LONGVARBINARY: number;
    static NULL: number;
    static OTHER: number;
    static JAVA_OBJECT: number;
    static DISTINCT: number;
    static STRUCT: number;
    static ARRAY: number;
    static BLOB: number;
    static CLOB: number;
    static REF: number;
    static DATALINK: number;
    static BOOLEAN: number;
    static ROWID: number;
    static NCHAR: number;
    static NVARCHAR: number;
    static LONGNVARCHAR: number;
    static NCLOB: number;
    static BASE64: number;
    static SQLXML: number;
    static getSQLTypeValue(type: string): number;
    static getSQLTypeKey(type: number): string;
    static parseUsingSQLType(arg: any, type: string): any;
    static isNumericSQLType(arg: number): boolean;
}
