import { AfterViewInit, ElementRef } from '@angular/core';
import { FormControl } from '@angular/forms';
import { MatCheckboxChange, MatDialogRef, MatSelectionList, MatSlideToggleChange } from '@angular/material';
import { Observable } from 'rxjs';
import { OColumnValueFilter } from '../../../../../types/o-column-value-filter.type';
import { TableFilterByColumnData } from '../../../../../types/o-table-filter-by-column-data.type';
import { OColumn } from '../../../column/o-column.class';
export declare class OTableFilterByColumnDataDialogComponent implements AfterViewInit {
    dialogRef: MatDialogRef<OTableFilterByColumnDataDialogComponent>;
    column: OColumn;
    preloadValues: boolean;
    mode: string;
    private isCustomFilterSubject;
    isCustomFilter: Observable<boolean>;
    private isDefaultFilterSubject;
    isDefaultFilter: Observable<boolean>;
    fcText: FormControl;
    fcFrom: FormControl;
    fcTo: FormControl;
    protected columnData: Array<TableFilterByColumnData>;
    protected tableData: Array<any>;
    private listDataSubject;
    protected _listData: Observable<Array<TableFilterByColumnData>>;
    filter: ElementRef;
    filterValueList: MatSelectionList;
    constructor(dialogRef: MatDialogRef<OTableFilterByColumnDataDialogComponent>, data: any);
    ngAfterViewInit(): void;
    listData: Observable<Array<TableFilterByColumnData>>;
    initializeDataList(filter?: OColumnValueFilter): void;
    initializeFilterEvent(): void;
    initializeCustomFilterValues(filter: OColumnValueFilter): void;
    readonly selectedValues: Array<TableFilterByColumnData>;
    areAllSelected(): boolean;
    isIndeterminate(): boolean;
    onSelectAllChange(event: MatCheckboxChange): void;
    getDistinctValues(data: Array<any>, filter: OColumnValueFilter): void;
    getColumnValuesFilter(): OColumnValueFilter;
    onSlideChange(e: MatSlideToggleChange): void;
    isTextType(): boolean;
    isNumericType(): boolean;
    isDateType(): boolean;
    getRowValue(i: number): any;
    getFixedDimensionClass(): boolean;
    protected getTypedValue(control: FormControl): any;
    protected getColumnDataUsingRenderer(): any[];
}
