import { Injector } from '@angular/core';
import { IComponent } from '../interfaces/component.interface';
import { OTranslateService } from '../services/translate/o-translate.service';
import { OPermissions } from '../types/o-permissions.type';
export declare class OBaseComponent implements IComponent {
    protected oattr: string;
    protected _olabel: string;
    protected oplaceholder: string;
    protected _enabled: boolean;
    protected _readOnly: boolean;
    protected _orequired: boolean;
    protected injector: Injector;
    protected translateService: OTranslateService;
    protected _isReadOnly: boolean;
    protected _tooltip: string;
    protected _tooltipPosition: string;
    protected _tooltipShowDelay: number;
    protected _tooltipHideDelay: number;
    protected permissions: OPermissions;
    constructor(injector: Injector);
    initialize(): void;
    getAttribute(): string;
    setEnabled(value: boolean): void;
    placeHolder: string;
    readonly tooltipClass: string;
    protected getTooltipClass(): string;
    protected getTooltipText(): string;
    tooltip: string;
    tooltipPosition: string;
    tooltipShowDelay: number;
    tooltipHideDelay: number;
    isReadOnly: boolean;
    protected setIsReadOnly(value: boolean): void;
    readOnly: any;
    orequired: boolean;
    readonly isRequired: boolean;
    required: boolean;
    enabled: any;
    olabel: string;
}
