import { AfterViewInit, ComponentFactoryResolver, ElementRef, EventEmitter, Injector, OnDestroy, QueryList, ViewContainerRef } from '@angular/core';
import { MatTabChangeEvent, MatTabGroup } from '@angular/material';
import { Router } from '@angular/router';
import { BehaviorSubject, Subscription } from 'rxjs';
import { DialogService } from '../../../services/dialog.service';
import { FormLayoutDetailComponentData } from '../../../types/form-layout-detail-component-data.type';
import { OFormLayoutManagerContentDirective } from '../directives/o-form-layout-manager-content.directive';
import { OFormLayoutManagerComponent } from '../o-form-layout-manager.component';
import { OFormLayoutTabGroup } from '../../../interfaces/o-form-layout-tab-group.interface';
export declare const DEFAULT_INPUTS_O_FORM_LAYOUT_TABGROUP: string[];
export declare const DEFAULT_OUTPUTS_O_FORM_LAYOUT_TABGROUP: string[];
export declare class OFormLayoutTabGroupComponent implements OFormLayoutTabGroup, AfterViewInit, OnDestroy {
    protected injector: Injector;
    protected componentFactoryResolver: ComponentFactoryResolver;
    protected location: ViewContainerRef;
    protected elRef: ElementRef;
    protected formLayoutManager: OFormLayoutManagerComponent;
    data: FormLayoutDetailComponentData[];
    selectedTabIndex: number | null;
    title: string;
    options: any;
    showLoading: BehaviorSubject<boolean>;
    protected _state: any;
    tabGroup: MatTabGroup;
    tabsDirectives: QueryList<OFormLayoutManagerContentDirective>;
    protected closeTabSubscription: Subscription;
    protected tabsDirectivesSubscription: Subscription;
    protected router: Router;
    protected loading: boolean;
    protected dialogService: DialogService;
    onMainTabSelected: EventEmitter<any>;
    onSelectedTabChange: EventEmitter<any>;
    onCloseTab: EventEmitter<any>;
    constructor(injector: Injector, componentFactoryResolver: ComponentFactoryResolver, location: ViewContainerRef, elRef: ElementRef, formLayoutManager: OFormLayoutManagerComponent);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    readonly disableAnimation: any;
    readonly headerPosition: any;
    readonly color: any;
    readonly backgroundColor: any;
    readonly templateMatTabLabel: any;
    readonly icon: any;
    readonly isIconPositionLeft: boolean;
    addTab(compData: FormLayoutDetailComponentData): void;
    reloadTab(compData: FormLayoutDetailComponentData): void;
    onTabSelectChange(arg: MatTabChangeEvent): void;
    closeTab(id: string): void;
    createTabComponent(tabData: FormLayoutDetailComponentData, content: OFormLayoutManagerContentDirective): void;
    getFormCacheData(idArg: string): FormLayoutDetailComponentData;
    getLastTabId(): string;
    getRouteOfActiveItem(): any[];
    setModifiedState(modified: boolean, id: string): void;
    updateNavigation(data: any, id: string, insertionMode?: boolean): void;
    updateActiveData(data: any): void;
    getDataToStore(): object;
    initializeComponentState(state: any): void;
    protected createTabsFromState(): void;
    protected createDetailComponent(component: any, paramsObj: any): FormLayoutDetailComponentData;
    state: any;
    getParams(): any;
    readonly elementRef: ElementRef;
}
