import { AfterViewInit, ElementRef, Injector, OnInit } from '@angular/core';
import { ValidatorFn } from '@angular/forms';
import { NgxMaterialTimepickerComponent } from 'ngx-material-timepicker';
import { FormValueOptions } from '../../../types/form-value-options.type';
import { OFormComponent } from '../../form/o-form.component';
import { OFormDataComponent } from '../../o-form-data-component.class';
export declare type OHourValueType = 'string' | 'timestamp';
export declare const DEFAULT_INPUTS_O_HOUR_INPUT: string[];
export declare const DEFAULT_OUTPUTS_O_HOUR_INPUT: string[];
export declare class OHourInputComponent extends OFormDataComponent implements OnInit, AfterViewInit {
    textInputEnabled: boolean;
    min: string;
    max: string;
    protected _format: number;
    protected onKeyboardInputDone: boolean;
    protected _valueType: OHourValueType;
    picker: NgxMaterialTimepickerComponent;
    constructor(form: OFormComponent, elRef: ElementRef, injector: Injector);
    ngAfterViewInit(): void;
    onKeyDown(e: KeyboardEvent): void;
    innerOnBlur(event: any): void;
    registerOnFormControlChange(): void;
    readonly formatString: string;
    open(e?: Event): void;
    setTime(event: any): void;
    setTimestampValue(value: any, options?: FormValueOptions): void;
    resolveValidators(): ValidatorFn[];
    onFormControlChange(value: any): void;
    format: number;
    valueType: any;
    convertToOHourValueType(val: any): OHourValueType;
    onChangeEvent(arg: any): void;
    onTimepickerChange(event: string): void;
    protected modifyPickerMethods(): void;
    ensureOFormValue(arg: any): void;
    protected updateValeOnInputChange(blurEvent: any): void;
    protected parseHour(value: string): string;
    protected emitOnValueChange(type: any, newValue: any, oldValue: any): void;
    getValue(): any;
    protected getValueAsString(val: any): string;
    protected convertToFormatString(value: any): string;
}
