import { SelectionModel } from '@angular/cdk/collections';
import { AfterContentInit, AfterViewInit, ElementRef, EventEmitter, Injector, OnChanges, OnDestroy, OnInit, QueryList, SimpleChange } from '@angular/core';
import { Subscription } from 'rxjs';
import { IListItem } from '../../interfaces/o-list-item.interface';
import { IList } from '../../interfaces/o-list.interface';
import { OListInitializationOptions } from '../../types/o-list-initialization-options.type';
import { OQueryDataArgs } from '../../types/query-data-args.type';
import { SQLOrder } from '../../types/sql-order.type';
import { OFormComponent } from '../form/o-form.component';
import { OServiceComponent } from '../o-service-component.class';
import { OListItemDirective } from './list-item/o-list-item.directive';
export declare const DEFAULT_INPUTS_O_LIST: string[];
export declare const DEFAULT_OUTPUTS_O_LIST: string[];
export declare class OListComponent extends OServiceComponent implements IList, AfterContentInit, AfterViewInit, OnDestroy, OnInit, OnChanges {
    listItemComponents: IListItem[];
    listItemDirectives: QueryList<OListItemDirective>;
    refreshButton: boolean;
    selectable: boolean;
    odense: boolean;
    deleteButton: boolean;
    insertButtonFloatable: boolean;
    quickFilterColumns: string;
    route: string;
    sortColumns: string;
    sortColArray: SQLOrder[];
    onClick: EventEmitter<any>;
    onDoubleClick: EventEmitter<any>;
    onInsertButtonClick: EventEmitter<any>;
    onItemDeleted: EventEmitter<any>;
    onDataLoaded: EventEmitter<any>;
    onPaginatedDataLoaded: EventEmitter<any>;
    selection: SelectionModel<Element>;
    enabledDeleteButton: boolean;
    insertButtonPosition: 'top' | 'bottom';
    protected dataResponseArray: any[];
    protected storePaginationState: boolean;
    protected subscription: Subscription;
    constructor(injector: Injector, elRef: ElementRef, form: OFormComponent);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterContentInit(): void;
    ngOnDestroy(): void;
    ngOnChanges(changes: {
        [propName: string]: SimpleChange;
    }): void;
    getComponentKey(): string;
    initialize(): void;
    reinitialize(options: OListInitializationOptions): void;
    registerListItemDirective(item: OListItemDirective): void;
    getDense(): boolean;
    onListItemClicked(onNext: (item: OListItemDirective) => void): object;
    onItemDetailClick(item: OListItemDirective | IListItem): void;
    onItemDetailDoubleClick(item: OListItemDirective | IListItem): void;
    getDataToStore(): object;
    reloadData(): void;
    reloadPaginatedDataFromStart(): void;
    filterData(value: string, loadMore?: boolean): void;
    isItemSelected(item: any): boolean;
    updateSelectedState(item: object, isSelected: boolean): void;
    onScroll(e: Event): void;
    remove(clearSelectedItems?: boolean): void;
    add(e?: Event): void;
    parseSortColumns(): void;
    getQueryArguments(filter: object, ovrrArgs?: OQueryDataArgs): any[];
    registerItem(item: IListItem): void;
    protected setListItemDirectivesData(): void;
    protected saveDataNavigationInLocalStorage(): void;
    protected setData(data: any, sqlTypes?: any, replace?: boolean): void;
}
