import { AfterViewInit, ChangeDetectorRef, ComponentFactoryResolver, ElementRef, Injector, OnDestroy, QueryList, ViewContainerRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { OTranslateService } from '../../services/translate/o-translate.service';
export declare const DEFAULT_INPUTS_O_MENU_CARD: string[];
export declare const DEFAULT_OUTPUTS_O_MENU_CARD: any[];
export declare class OCardMenuItemComponent implements AfterViewInit, OnDestroy {
    protected injector: Injector;
    protected router: Router;
    protected actRoute: ActivatedRoute;
    protected resolver: ComponentFactoryResolver;
    protected cd: ChangeDetectorRef;
    protected elRef: ElementRef;
    title: string;
    image: string;
    icon: string;
    tooltip: string;
    buttonText: string;
    disabledButton: boolean;
    mainContainerLayout: string;
    secondaryContainerLayout: string;
    route: string;
    action: () => void;
    detailComponent: any;
    detailComponentInputs: object;
    protected _detailComponentContainer: ViewContainerRef;
    detailComponentContainer: ViewContainerRef;
    protected translateService: OTranslateService;
    protected translateServiceSubscription: Subscription;
    secondaryContent: QueryList<any>;
    protected _showSecondaryContainer: boolean;
    constructor(injector: Injector, router: Router, actRoute: ActivatedRoute, resolver: ComponentFactoryResolver, cd: ChangeDetectorRef, elRef: ElementRef);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    useImage(): boolean;
    useIcon(): boolean;
    onButtonClick(): void;
    onClick(): void;
    showSecondaryContainer: boolean;
}
